import type { PreflopStrategy } from '../types';

export const cash6max20bbMpVs3bet: PreflopStrategy = {
  id: 'cash-6max-20bb-mp-vs-3bet',
  title: 'Cash 6-max 20bb MP vs 3bet',
  meta: {
    format: 'CASH',
    players: 6,
    stackBB: 20,
    position: 'MP',
    action: 'vs-3bet',
    strategicNote: 'Con un stack de 20bb, al enfrentar un 3-bet desde MP, la estrategia se vuelve extremadamente polarizada. Se va all-in con un rango de valor muy fuerte y se pagan algunas manos especulativas con buenas odds. Las decisiones postflop son mínimas, ya que el pozo suele ser muy grande en relación con el stack restante. La mayoría de las manos se retiran para evitar situaciones de "coin flip" o dominadas.',
  },
  stats: {
    raise: 0,
    call: 1.8,
    fold: 15.2,
    allin: 7.1,
  },
  range: {
    "AA":  { "allin": 100,  "raise": 0, "call": 0,    "fold": 0 },
    "AKs": { "allin": 100,  "raise": 0, "call": 0,    "fold": 0 },
    "AQs": { "allin": 100,  "raise": 0, "call": 0,    "fold": 0 },
    "AJs": { "allin": 98.5, "raise": 0, "call": 1.5,  "fold": 0 },
    "ATs": { "allin": 79,   "raise": 0, "call": 21,   "fold": 0 },
    "A9s": { "allin": 0,    "raise": 0, "call": 31,   "fold": 69 },
    "A5s": { "allin": 0,    "raise": 0, "call": 31.5, "fold": 68.5 },
    "A4s": { "allin": 0,    "raise": 0, "call": 53.5, "fold": 46.5 },
    "AKo": { "allin": 100,  "raise": 0, "call": 0,    "fold": 0 },
    "KK":  { "allin": 100,  "raise": 0, "call": 0,    "fold": 0 },
    "KQs": { "allin": 50.5, "raise": 0, "call": 49.5, "fold": 0 },
    "KJs": { "allin": 77,   "raise": 0, "call": 23,   "fold": 0 },
    "KTs": { "allin": 59,   "raise": 0, "call": 41,   "fold": 0 },
    "K7s": { "allin": 0,    "raise": 0, "call": 23,   "fold": 77 },
    "K6s": { "allin": 0,    "raise": 0, "call": 29.5, "fold": 70.5 },
    "AQo": { "allin": 100,  "raise": 0, "call": 0,    "fold": 0 },
    "QQ":  { "allin": 100,  "raise": 0, "call": 0,    "fold": 0 },
    "QJs": { "allin": 0,    "raise": 0, "call": 31,   "fold": 69 },
    "QTs": { "allin": 0,    "raise": 0, "call": 26,   "fold": 74 },
    "AJo": { "allin": 13,   "raise": 0, "call": 14.5, "fold": 72.5 },
    "JJ":  { "allin": 100,  "raise": 0, "call": 0,    "fold": 0 },
    "JTs": { "allin": 0,    "raise": 0, "call": 23,   "fold": 77 },
    "TT":  { "allin": 100,  "raise": 0, "call": 0,    "fold": 0 },
    "T9s": { "allin": 0,    "raise": 0, "call": 36.5, "fold": 63.5 },
    "99":  { "allin": 100,  "raise": 0, "call": 0,    "fold": 0 },
    "88":  { "allin": 100,  "raise": 0, "call": 0,    "fold": 0 },
    "77":  { "allin": 60,   "raise": 0, "call": 40,   "fold": 0 },
    "66":  { "allin": 13.5, "raise": 0, "call": 56.5, "fold": 30 }
  },
};
