import type { PreflopStrategy } from '../types';

export const cash6max40bbUtgRfi: PreflopStrategy = {
  id: 'cash-6max-40bb-utg-rfi',
  title: 'Cash 6-max 40bb UTG RFI',
  meta: {
    format: 'CASH',
    players: 6,
    stackBB: 40,
    position: 'UTG',
    action: 'RFI',
    strategicNote: 'Con un stack de 40bb desde UTG, el rango de apertura sigue siendo ajustado, pero empezamos a incluir más manos que juegan bien all-in o en pozos 3-beteados, como pares medios y algunos broadways. La estrategia se inclina hacia la simplicidad y la realización de equity.',
  },
  stats: {
    raise: 19.7,
    call: 0.0,
    fold: 80.3,
    allin: 0.0,
  },
  range: {
    "AA": { "allin": 0, "raise": 100, "call": 0, "fold": 0 },
    "AKs": { "allin": 0, "raise": 100, "call": 0, "fold": 0 },
    "AQs": { "allin": 0, "raise": 100, "call": 0, "fold": 0 },
    "AJs": { "allin": 0, "raise": 100, "call": 0, "fold": 0 },
    "ATs": { "allin": 0, "raise": 100, "call": 0, "fold": 0 },
    "A9s": { "allin": 0, "raise": 100, "call": 0, "fold": 0 },
    "A8s": { "allin": 0, "raise": 100, "call": 0, "fold": 0 },
    "A7s": { "allin": 0, "raise": 100, "call": 0, "fold": 0 },
    "A6s": { "allin": 0, "raise": 100, "call": 0, "fold": 0 },
    "A5s": { "allin": 0, "raise": 100, "call": 0, "fold": 0 },
    "A4s": { "allin": 0, "raise": 100, "call": 0, "fold": 0 },
    "A3s": { "allin": 0, "raise": 100, "call": 0, "fold": 0 },
    "A2s": { "allin": 0, "raise": 46.5, "call": 0, "fold": 53.5 },
    "AKo": { "allin": 0, "raise": 100, "call": 0, "fold": 0 },
    "KK": { "allin": 0, "raise": 100, "call": 0, "fold": 0 },
    "KQs": { "allin": 0, "raise": 100, "call": 0, "fold": 0 },
    "KJs": { "allin": 0, "raise": 100, "call": 0, "fold": 0 },
    "KTs": { "allin": 0, "raise": 100, "call": 0, "fold": 0 },
    "K9s": { "allin": 0, "raise": 100, "call": 0, "fold": 0 },
    "K8s": { "allin": 0, "raise": 100, "call": 0, "fold": 0 },
    "K7s": { "allin": 0, "raise": 29.5, "call": 0, "fold": 70.5 },
    "K6s": { "allin": 0, "raise": 50.5, "call": 0, "fold": 49.5 },
    "AQo": { "allin": 0, "raise": 100, "call": 0, "fold": 0 },
    "KQo": { "allin": 0, "raise": 100, "call": 0, "fold": 0 },
    "QQ": { "allin": 0, "raise": 100, "call": 0, "fold": 0 },
    "QJs": { "allin": 0, "raise": 100, "call": 0, "fold": 0 },
    "QTs": { "allin": 0, "raise": 100, "call": 0, "fold": 0 },
    "Q9s": { "allin": 0, "raise": 100, "call": 0, "fold": 0 },
    "AJo": { "allin": 0, "raise": 100, "call": 0, "fold": 0 },
    "KJo": { "allin": 0, "raise": 100, "call": 0, "fold": 0 },
    "QJo": { "allin": 0, "raise": 100, "call": 0, "fold": 0 },
    "JJ": { "allin": 0, "raise": 100, "call": 0, "fold": 0 },
    "JTs": { "allin": 0, "raise": 100, "call": 0, "fold": 0 },
    "J9s": { "allin": 0, "raise": 100, "call": 0, "fold": 0 },
    "ATo": { "allin": 0, "raise": 100, "call": 0, "fold": 0 },
    "KTo": { "allin": 0, "raise": 61.5, "call": 0, "fold": 38.5 },
    "QTo": { "allin": 0, "raise": 30, "call": 0, "fold": 70 },
    "JTo": { "allin": 0, "raise": 27.5, "call": 0, "fold": 72.5 },
    "TT": { "allin": 0, "raise": 100, "call": 0, "fold": 0 },
    "T9s": { "allin": 0, "raise": 100, "call": 0, "fold": 0 },
    "T8s": { "allin": 0, "raise": 63, "call": 0, "fold": 37 },
    "99": { "allin": 0, "raise": 100, "call": 0, "fold": 0 },
    "98s": { "allin": 0, "raise": 75.5, "call": 0, "fold": 24.5 },
    "88": { "allin": 0, "raise": 100, "call": 0, "fold": 0 },
    "87s": { "allin": 0, "raise": 28.5, "call": 0, "fold": 71.5 },
    "77": { "allin": 0, "raise": 100, "call": 0, "fold": 0 },
    "66": { "allin": 0, "raise": 100, "call": 0, "fold": 0 },
    "55": { "allin": 0, "raise": 96, "call": 0, "fold": 4 },
    "44": { "allin": 0, "raise": 64.5, "call": 0, "fold": 35.5 },
    "33": { "allin": 0, "raise": 45, "call": 0, "fold": 55 },
    "22": { "allin": 0, "raise": 37.5, "call": 0, "fold": 62.5 }
  },
};
