import type { PreflopStrategy } from '../types';

export const cash6max40bbUtgVs3bet: PreflopStrategy = {
  id: 'cash-6max-40bb-utg-vs-3bet',
  title: 'Cash 6-max 40bb UTG vs 3bet',
  meta: {
    format: 'CASH',
    players: 6,
    stackBB: 40,
    position: 'UTG',
    action: 'vs-3bet',
    strategicNote: 'Desde UTG con 40bb, al enfrentar un 3-bet, la estrategia es polarizada. Vamos all-in con nuestras manos más premium (AA, KK, AK) y como bluff con bloqueadores (A5s-A3s). Pagamos con manos que tienen buen potencial post-flop y odds implícitas. El resto se foldea para evitar situaciones dominadas fuera de posición.',
  },
  stats: {
    raise: 0.8,
    call: 7.5,
    fold: 88.6,
    allin: 3.1,
  },
  range: {
    "AA":  { "allin": 42,   "raise": 56,   "call": 2,    "fold": 0 },
    "AKs": { "allin": 98.5, "raise": 1.5,  "call": 0,    "fold": 0 },
    "AQs": { "allin": 0,    "raise": 7,    "call": 93,   "fold": 0 },
    "AJs": { "allin": 0,    "raise": 11.5, "call": 88.5, "fold": 0 },
    "ATs": { "allin": 0,    "raise": 11,   "call": 89,   "fold": 0 },
    "A9s": { "allin": 0,    "raise": 0,    "call": 68,   "fold": 32 },
    "A8s": { "allin": 0,    "raise": 0,    "call": 32,   "fold": 68 },
    "A7s": { "allin": 0,    "raise": 5,    "call": 44.5, "fold": 50.5 },
    "A6s": { "allin": 0,    "raise": 0,    "call": 49.5, "fold": 50.5 },
    "A5s": { "allin": 100,  "raise": 0,    "call": 0,    "fold": 0 },
    "A4s": { "allin": 100,  "raise": 0,    "call": 0,    "fold": 0 },
    "A3s": { "allin": 6,    "raise": 9,    "call": 85,   "fold": 0 },
    "AKo": { "allin": 100,  "raise": 0,    "call": 0,    "fold": 0 },
    "KK":  { "allin": 95.5, "raise": 4.5,  "call": 0,    "fold": 0 },
    "KQs": { "allin": 0,    "raise": 5,    "call": 95,   "fold": 0 },
    "KJs": { "allin": 0,    "raise": 9.5,  "call": 90.5, "fold": 0 },
    "KTs": { "allin": 0,    "raise": 10.5, "call": 89.5, "fold": 0 },
    "K9s": { "allin": 0,    "raise": 0,    "call": 45.5, "fold": 54.5 },
    "K8s": { "allin": 0,    "raise": 0,    "call": 29.5, "fold": 70.5 },
    "AQo": { "allin": 0,    "raise": 13,   "call": 87,   "fold": 0 },
    "KQo": { "allin": 0,    "raise": 0,    "call": 17,   "fold": 83 },
    "QQ":  { "allin": 87,   "raise": 13,   "call": 0,    "fold": 0 },
    "QJs": { "allin": 0,    "raise": 1.5,  "call": 98.5, "fold": 0 },
    "QTs": { "allin": 0,    "raise": 0,    "call": 100,  "fold": 0 },
    "JJ":  { "allin": 52,   "raise": 7.5,  "call": 40.5, "fold": 0 },
    "JTs": { "allin": 0,    "raise": 6.5,  "call": 93.5, "fold": 0 },
    "J9s": { "allin": 0,    "raise": 0,    "call": 96.5, "fold": 3.5 },
    "TT":  { "allin": 0,    "raise": 16,   "call": 84,   "fold": 0 },
    "T9s": { "allin": 0,    "raise": 0.5,  "call": 99.5, "fold": 0 },
    "99":  { "allin": 0,    "raise": 4.5,  "call": 95.5, "fold": 0 },
    "88":  { "allin": 0,    "raise": 1,    "call": 99,   "fold": 0 },
    "77":  { "allin": 0,    "raise": 0,    "call": 100,  "fold": 0 },
    "66":  { "allin": 10,   "raise": 0,    "call": 90,   "fold": 0 },
    "55":  { "allin": 0,    "raise": 0,    "call": 100,  "fold": 0 }
  },
};
