import type { PreflopStrategy } from '../types';

export const cash6max20bbUtgRfi: PreflopStrategy = {
  id: 'cash-6max-20bb-utg-rfi',
  title: 'Cash 6-max 20bb UTG RFI',
  meta: {
    format: 'CASH',
    players: 6,
    stackBB: 20,
    position: 'UTG',
    action: 'RFI',
    strategicNote: 'Con un stack de 20bb desde UTG, nuestra estrategia de RFI es muy ajustada. Se abren principalmente manos fuertes para ir all-in post-flop con comodidad o para tener una buena equity si nos pagan. El rango es casi exclusivamente de raise o fold, eliminando los calls para no crear pozos multi-way fuera de posición con un stack comprometido.',
  },
  stats: {
    raise: 18.8,
    call: 0.0,
    fold: 81.2,
    allin: 0.0,
  },
  range: {
    "AA": { "raise": 100 },
    "AKs": { "raise": 100 },
    "AQs": { "raise": 100 },
    "AJs": { "raise": 100 },
    "ATs": { "raise": 100 },
    "A9s": { "raise": 100 },
    "A8s": { "raise": 100 },
    "A7s": { "raise": 100 },
    "A6s": { "raise": 100 },
    "A5s": { "raise": 100 },
    "A4s": { "raise": 100 },
    "A3s": { "raise": 100 },
    "AKo": { "raise": 100 },
    "KK": { "raise": 100 },
    "KQs": { "raise": 100 },
    "KJs": { "raise": 100 },
    "KTs": { "raise": 100 },
    "K9s": { "raise": 100 },
    "K8s": { "raise": 100 },
    "K7s": { "raise": 100 },
    "K6s": { "raise": 10.5, "fold": 89.5 },
    "AQo": { "raise": 100 },
    "KQo": { "raise": 100 },
    "QQ": { "raise": 100 },
    "QJs": { "raise": 100 },
    "QTs": { "raise": 100 },
    "Q9s": { "raise": 100 },
    "Q8s": { "raise": 100 },
    "AJo": { "raise": 100 },
    "KJo": { "raise": 100 },
    "QJo": { "raise": 99.5, "fold": 0.5 },
    "JJ": { "raise": 100 },
    "JTs": { "raise": 100 },
    "J9s": { "raise": 75.5, "fold": 24.5 },
    "ATo": { "raise": 100 },
    "KTo": { "raise": 34, "fold": 66 },
    "QTo": { "raise": 8, "fold": 92 },
    "TT": { "raise": 100 },
    "T9s": { "raise": 100 },
    "T8s": { "raise": 26, "fold": 74 },
    "A9o": { "raise": 80.5, "fold": 19.5 },
    "99": { "raise": 100 },
    "98s": { "raise": 35, "fold": 65 },
    "88": { "raise": 100 },
    "77": { "raise": 100 },
    "66": { "raise": 32, "fold": 68 },
    "55": { "raise": 4.5, "fold": 95.5 },
  },
};
