import type { PreflopStrategy } from '../types';

export const cash6max20bbSbVsOpen: PreflopStrategy = {
  id: 'cash-6max-20bb-sb-vs-open',
  title: 'Cash 6-max 20bb SB vs Open 2.5x',
  meta: {
    format: 'CASH',
    players: 6,
    stackBB: 20,
    position: 'SB',
    action: 'vs-open',
    strategicNote: 'Con 20bb en la Ciega Pequeña (SB) contra una apertura, la estrategia es muy agresiva. El objetivo es 3-betear o ir all-in con un rango polarizado para maximizar la fold equity o jugar por todo el stack con ventaja. El call es menos frecuente, ya que jugar fuera de posición con un stack corto puede ser complicado.',
  },
  stats: {
    raise: 4.9,
    call: 0.6,
    fold: 90.5,
    allin: 4.0,
  },
  range: {
    "AA": { "allin": 0, "raise": 97.5, "call": 2.5, "fold": 0 },
    "AKs": { "allin": 0, "raise": 100, "call": 0, "fold": 0 },
    "AQs": { "allin": 44, "raise": 56, "call": 0, "fold": 0 },
    "AJs": { "allin": 94.53, "raise": 0.99, "call": 4.48, "fold": 0 },
    "ATs": { "allin": 67, "raise": 11.5, "call": 21.5, "fold": 0 },
    "A9s": { "allin": 0, "raise": 29, "call": 17, "fold": 54 },
    "A7s": { "allin": 0, "raise": 100, "call": 0, "fold": 0 },
    "A5s": { "allin": 0, "raise": 0, "call": 6, "fold": 94 },
    "AKo": { "allin": 89.5, "raise": 10.5, "call": 0, "fold": 0 },
    "AQo": { "allin": 53.5, "raise": 46.5, "call": 0, "fold": 0 },
    "AJo": { "allin": 0, "raise": 74.87, "call": 6.53, "fold": 18.6 },
    "A8o": { "allin": 0, "raise": 40.5, "call": 0, "fold": 59.5 },
    "KK": { "allin": 0, "raise": 100, "call": 0, "fold": 0 },
    "KQs": { "allin": 70.5, "raise": 20.5, "call": 9, "fold": 0 },
    "KJs": { "allin": 68.84, "raise": 17.59, "call": 13.57, "fold": 0 },
    "KTs": { "allin": 97, "raise": 0, "call": 3, "fold": 0 },
    "KQo": { "allin": 0, "raise": 76.12, "call": 4.98, "fold": 18.9 },
    "QQ": { "allin": 0, "raise": 100, "call": 0, "fold": 0 },
    "QJs": { "allin": 91, "raise": 0, "call": 9, "fold": 0 },
    "QTs": { "allin": 0, "raise": 0, "call": 9, "fold": 91 },
    "JJ": { "allin": 0, "raise": 100, "call": 0, "fold": 0 },
    "TT": { "allin": 50.5, "raise": 49.5, "call": 0, "fold": 0 },
    "99": { "allin": 100, "raise": 0, "call": 0, "fold": 0 },
    "88": { "allin": 87, "raise": 13, "call": 0, "fold": 0 },
    "77": { "allin": 0, "raise": 90.5, "call": 9.5, "fold": 0 },
    "66": { "allin": 0, "raise": 0, "call": 10.5, "fold": 89.5 },
    "55": { "allin": 33.5, "raise": 4, "call": 37.5, "fold": 25 }
  },
};
