import type { PreflopStrategy } from '../types';

export const cash6max100bbMpRfi: PreflopStrategy = {
  id: 'cash-6max-100bb-mp-rfi',
  title: 'Cash 6-max 100bb MP RFI',
  meta: {
    format: 'CASH',
    players: 6,
    stackBB: 100,
    position: 'MP',
    action: 'RFI',
    strategicNote: 'Desde MP en una mesa de 6-max, nuestro rango de apertura es más amplio que desde UTG. Podemos abrir manos más especulativas como suited connectors y pares medios con más frecuencia, aprovechando la posición sobre los jugadores que quedan por hablar. Sin embargo, todavía debemos ser selectivos, ya que hay jugadores en CO, BTN y las ciegas que pueden 3-betear.',
  },
  stats: {
    raise: 18.7,
    call: 0.0,
    fold: 81.3,
    allin: 0.0,
  },
  range: {
    "AA": { "raise": 100, "fold": 0, "call": 0, "allin": 0 },
    "AKs": { "raise": 100, "fold": 0, "call": 0, "allin": 0 },
    "AQs": { "raise": 100, "fold": 0, "call": 0, "allin": 0 },
    "AJs": { "raise": 100, "fold": 0, "call": 0, "allin": 0 },
    "ATs": { "raise": 100, "fold": 0, "call": 0, "allin": 0 },
    "A9s": { "raise": 100, "fold": 0, "call": 0, "allin": 0 },
    "A8s": { "raise": 100, "fold": 0, "call": 0, "allin": 0 },
    "A7s": { "raise": 100, "fold": 0, "call": 0, "allin": 0 },
    "A6s": { "raise": 100, "fold": 0, "call": 0, "allin": 0 },
    "A5s": { "raise": 100, "fold": 0, "call": 0, "allin": 0 },
    "A4s": { "raise": 73, "fold": 27, "call": 0, "allin": 0 },
    "A3s": { "raise": 16, "fold": 84, "call": 0, "allin": 0 },
    "AKo": { "raise": 100, "fold": 0, "call": 0, "allin": 0 },
    "AQo": { "raise": 100, "fold": 0, "call": 0, "allin": 0 },
    "KK": { "raise": 100, "fold": 0, "call": 0, "allin": 0 },
    "QQ": { "raise": 100, "fold": 0, "call": 0, "allin": 0 },
    "JJ": { "raise": 100, "fold": 0, "call": 0, "allin": 0 },
    "TT": { "raise": 100, "fold": 0, "call": 0, "allin": 0 },
    "KQs": { "raise": 100, "fold": 0, "call": 0, "allin": 0 },
    "KJs": { "raise": 100, "fold": 0, "call": 0, "allin": 0 },
    "KTs": { "raise": 100, "fold": 0, "call": 0, "allin": 0 },
    "K9s": { "raise": 100, "fold": 0, "call": 0, "allin": 0 },
    "K8s": { "raise": 50, "fold": 50, "call": 0, "allin": 0 },
    "K7s": { "raise": 50, "fold": 50, "call": 0, "allin": 0 },
    "K6s": { "raise": 50, "fold": 50, "call": 0, "allin": 0 },
    "K5s": { "raise": 50, "fold": 50, "call": 0, "allin": 0 },
    "KQo": { "raise": 59, "fold": 41, "call": 0, "allin": 0 },
    "QJs": { "raise": 93, "fold": 7, "call": 0, "allin": 0 },
    "JTs": { "raise": 22, "fold": 78, "call": 0, "allin": 0 },
    "99": { "raise": 77, "fold": 23, "call": 0, "allin": 0 },
    "88": { "raise": 41, "fold": 59, "call": 0, "allin": 0 },
    "77": { "raise": 39, "fold": 61, "call": 0, "allin": 0 },
    "66": { "raise": 27, "fold": 73, "call": 0, "allin": 0 },
    "65s": { "raise": 35, "fold": 65, "call": 0, "allin": 0 },
    "55": { "raise": 10, "fold": 90, "call": 0, "allin": 0 },
    "54s": { "raise": 24, "fold": 76, "call": 0, "allin": 0 },
    "44": { "raise": 12, "fold": 88, "call": 0, "allin": 0 },
    "33": { "raise": 12, "fold": 88, "call": 0, "allin": 0 },
    "22": { "raise": 8, "fold": 92, "call": 0, "allin": 0 }
  },
};
