import type { PreflopStrategy } from '../types';

export const cash6max40bbMpRfi: PreflopStrategy = {
  id: 'cash-6max-40bb-mp-rfi',
  title: 'Cash 6-max 40bb MP RFI',
  meta: {
    format: 'CASH',
    players: 6,
    stackBB: 40,
    position: 'MP',
    action: 'RFI',
    strategicNote: 'Con 40bb en MP, el rango de RFI se amplía en comparación con UTG. Se abren más manos especulativas como suited connectors y broadways, pero la estrategia sigue siendo consciente de los 3-bets de los jugadores en posición (CO y BTN).',
  },
  stats: {
    raise: 26.2,
    call: 0,
    fold: 73.8,
    allin: 0,
  },
  range: {
    "AA": { "allin": 0, "raise": 100, "call": 0, "fold": 0 },
    "AKs": { "allin": 0, "raise": 100, "call": 0, "fold": 0 },
    "AQs": { "allin": 0, "raise": 100, "call": 0, "fold": 0 },
    "AJs": { "allin": 0, "raise": 100, "call": 0, "fold": 0 },
    "ATs": { "allin": 0, "raise": 100, "call": 0, "fold": 0 },
    "A9s": { "allin": 0, "raise": 100, "call": 0, "fold": 0 },
    "A8s": { "allin": 0, "raise": 100, "call": 0, "fold": 0 },
    "A7s": { "allin": 0, "raise": 100, "call": 0, "fold": 0 },
    "A6s": { "allin": 0, "raise": 100, "call": 0, "fold": 0 },
    "A5s": { "allin": 0, "raise": 100, "call": 0, "fold": 0 },
    "A4s": { "allin": 0, "raise": 100, "call": 0, "fold": 0 },
    "A3s": { "allin": 0, "raise": 100, "call": 0, "fold": 0 },
    "A2s": { "allin": 0, "raise": 100, "call": 0, "fold": 0 },
    "AKo": { "allin": 0, "raise": 100, "call": 0, "fold": 0 },
    "KK": { "allin": 0, "raise": 100, "call": 0, "fold": 0 },
    "KQs": { "allin": 0, "raise": 100, "call": 0, "fold": 0 },
    "KJs": { "allin": 0, "raise": 100, "call": 0, "fold": 0 },
    "KTs": { "allin": 0, "raise": 100, "call": 0, "fold": 0 },
    "K9s": { "allin": 0, "raise": 100, "call": 0, "fold": 0 },
    "K8s": { "allin": 0, "raise": 100, "call": 0, "fold": 0 },
    "K7s": { "allin": 0, "raise": 100, "call": 0, "fold": 0 },
    "K6s": { "allin": 0, "raise": 100, "call": 0, "fold": 0 },
    "K5s": { "allin": 0, "raise": 56.5, "call": 0, "fold": 43.5 },
    "AQo": { "allin": 0, "raise": 100, "call": 0, "fold": 0 },
    "KQo": { "allin": 0, "raise": 100, "call": 0, "fold": 0 },
    "QQ": { "allin": 0, "raise": 100, "call": 0, "fold": 0 },
    "QJs": { "allin": 0, "raise": 100, "call": 0, "fold": 0 },
    "QTs": { "allin": 0, "raise": 100, "call": 0, "fold": 0 },
    "Q9s": { "allin": 0, "raise": 100, "call": 0, "fold": 0 },
    "Q8s": { "allin": 0, "raise": 100, "call": 0, "fold": 0 },
    "AJo": { "allin": 0, "raise": 100, "call": 0, "fold": 0 },
    "KJo": { "allin": 0, "raise": 100, "call": 0, "fold": 0 },
    "QJo": { "allin": 0, "raise": 100, "call": 0, "fold": 0 },
    "JJ": { "allin": 0, "raise": 100, "call": 0, "fold": 0 },
    "JTs": { "allin": 0, "raise": 100, "call": 0, "fold": 0 },
    "J9s": { "allin": 0, "raise": 100, "call": 0, "fold": 0 },
    "J8s": { "allin": 0, "raise": 100, "call": 0, "fold": 0 },
    "ATo": { "allin": 0, "raise": 100, "call": 0, "fold": 0 },
    "KTo": { "allin": 0, "raise": 100, "call": 0, "fold": 0 },
    "QTo": { "allin": 0, "raise": 88, "call": 0, "fold": 12 },
    "JTo": { "allin": 0, "raise": 27.5, "call": 0, "fold": 72.5 },
    "TT": { "allin": 0, "raise": 100, "call": 0, "fold": 0 },
    "T9s": { "allin": 0, "raise": 100, "call": 0, "fold": 0 },
    "T8s": { "allin": 0, "raise": 100, "call": 0, "fold": 0 },
    "A9o": { "allin": 0, "raise": 100, "call": 0, "fold": 0 },
    "99": { "allin": 0, "raise": 100, "call": 0, "fold": 0 },
    "98s": { "allin": 0, "raise": 100, "call": 0, "fold": 0 },
    "97s": { "allin": 0, "raise": 35, "call": 0, "fold": 65 },
    "88": { "allin": 0, "raise": 100, "call": 0, "fold": 0 },
    "87s": { "allin": 0, "raise": 28.5, "call": 0, "fold": 71.5 },
    "77": { "allin": 0, "raise": 100, "call": 0, "fold": 0 },
    "76s": { "allin": 0, "raise": 11, "call": 0, "fold": 89 },
    "66": { "allin": 0, "raise": 100, "call": 0, "fold": 0 },
    "65s": { "allin": 0, "raise": 9.5, "call": 0, "fold": 90.5 },
    "55": { "allin": 0, "raise": 100, "call": 0, "fold": 0 },
    "44": { "allin": 0, "raise": 64.5, "call": 0, "fold": 35.5 },
    "33": { "allin": 0, "raise": 45, "call": 0, "fold": 55 },
    "22": { "allin": 0, "raise": 37.5, "call": 0, "fold": 62.5 }
  }
};
