import type { PreflopStrategy } from '../types';

export const cash6max20bbBtnVsOpen: PreflopStrategy = {
  id: 'cash-6max-20bb-btn-vs-open',
  title: 'Cash 6-max 20bb BTN vs Open 2.5x',
  meta: {
    format: 'CASH',
    players: 6,
    stackBB: 20,
    position: 'BTN',
    action: 'vs-open',
    strategicNote: "Desde el BTN con 20bb, al enfrentar una apertura de 2.5x, la estrategia es una mezcla de 3-bet (raise/all-in) y call. Se hace 3-bet all-in por valor con un rango fuerte, se hacen 3-bets más pequeños como farol con manos que tienen buenos bloqueadores, y se paga con manos que tienen buen potencial post-flop. Dado el stack corto, la mayoría de las manos marginales se retiran.",
  },
  stats: {
    raise: 6.4,
    call: 0.6,
    fold: 90.5,
    allin: 2.5,
  },
  range: {
    "AA": { "allin": 0, "raise": 93, "call": 7, "fold": 0 }, 
    "AKs": { "allin": 0, "raise": 100, "call": 0, "fold": 0 }, 
    "AQs": { "allin": 0, "raise": 100, "call": 0, "fold": 0 }, 
    "AJs": { "allin": 0, "raise": 80.5, "call": 19.5, "fold": 0 }, 
    "ATs": { "allin": 0, "raise": 72, "call": 28, "fold": 0 }, 
    "A9s": { "allin": 0, "raise": 62.5, "call": 10, "fold": 27.5 }, 
    "A8s": { "allin": 0, "raise": 100, "call": 0, "fold": 0 }, 
    "A6s": { "allin": 0, "raise": 0, "call": 15.5, "fold": 84.5 },
    "AKo": { "allin": 48, "raise": 52, "call": 0, "fold": 0 }, 
    "AQo": { "allin": 81.5,"raise": 17, "call": 1.5, "fold": 0 }, 
    "AJo": { "allin": 0, "raise": 53, "call": 2, "fold": 45 },
    "KK": { "allin": 0, "raise": 100, "call": 0, "fold": 0 }, 
    "KQs": { "allin": 74.5,"raise": 0, "call": 25.5, "fold": 0 }, 
    "KJs": { "allin": 87.5,"raise": 0, "call": 12.5, "fold": 0 }, 
    "KTs": { "allin": 64.6766, "raise": 1.9901, "call": 5.4726, "fold": 27.8607 },
    "KQo": { "allin": 0, "raise": 100, "call": 0, "fold": 0 }, 
    "KJo": { "allin": 0, "raise": 15.5, "call": 0, "fold": 84.5 },
    "QQ": { "allin": 0, "raise": 100, "call": 0, "fold": 0 }, 
    "QJs": { "allin": 0, "raise": 0, "call": 6.5, "fold": 93.5 }, 
    "QTs": { "allin": 0, "raise": 0, "call": 5.5, "fold": 94.5 },
    "JJ": { "allin": 0, "raise": 100, "call": 0, "fold": 0 }, 
    "ATo": { "allin": 0, "raise": 28, "call": 0, "fold": 72 },
    "TT": { "allin": 41.5,"raise": 58.5, "call": 0, "fold": 0 }, 
    "99": { "allin": 98.5,"raise": 0, "call": 1.5, "fold": 0 }, 
    "88": { "allin": 6, "raise": 82.5, "call": 11.5, "fold": 0 }, 
    "77": { "allin": 0, "raise": 0, "call": 8.5, "fold": 91.5 }, 
    "66": { "allin": 0, "raise": 0, "call": 5.5, "fold": 94.5 }
  },
};
