import type { PreflopStrategy } from '../types';

export const cash6max100bbUtgRfi: PreflopStrategy = {
  id: 'cash-6max-100bb-utg-rfi',
  title: 'Cash 6-max 100bb UTG RFI',
  meta: {
    format: 'CASH',
    players: 6,
    stackBB: 100,
    position: 'UTG',
    action: 'RFI',
    strategicNote: 'Desde UTG en una mesa de 6-max, nuestro rango de apertura es el más ajustado. Solo jugamos las manos más fuertes para evitar situaciones postflop complicadas fuera de posición contra el resto de la mesa. La rentabilidad viene de la fuerza de nuestras cartas, no de la posición.',
  },
  stats: {
    raise: 18.7,
    call: 0.0,
    fold: 81.3,
    allin: 0.0,
  },
  range: {
    "AA": { "raise": 100, "fold": 0, "call": 0, "allin": 0 },
    "KK": { "raise": 100, "fold": 0, "call": 0, "allin": 0 },
    "QQ": { "raise": 100, "fold": 0, "call": 0, "allin": 0 },
    "JJ": { "raise": 100, "fold": 0, "call": 0, "allin": 0 },
    "TT": { "raise": 100, "fold": 0, "call": 0, "allin": 0 },
    "99": { "raise": 100, "fold": 0, "call": 0, "allin": 0 },
    "88": { "raise": 100, "fold": 0, "call": 0, "allin": 0 },
    "77": { "raise": 100, "fold": 0, "call": 0, "allin": 0 },
    "66": { "raise": 100, "fold": 0, "call": 0, "allin": 0 },
    "AKs": { "raise": 100, "fold": 0, "call": 0, "allin": 0 },
    "AQs": { "raise": 100, "fold": 0, "call": 0, "allin": 0 },
    "AJs": { "raise": 100, "fold": 0, "call": 0, "allin": 0 },
    "ATs": { "raise": 100, "fold": 0, "call": 0, "allin": 0 },
    "A9s": { "raise": 100, "fold": 0, "call": 0, "allin": 0 },
    "A8s": { "raise": 100, "fold": 0, "call": 0, "allin": 0 },
    "A7s": { "raise": 100, "fold": 0, "call": 0, "allin": 0 },
    "A6s": { "raise": 100, "fold": 0, "call": 0, "allin": 0 },
    "A5s": { "raise": 100, "fold": 0, "call": 0, "allin": 0 },
    "A4s": { "raise": 100, "fold": 0, "call": 0, "allin": 0 },
    "A3s": { "raise": 100, "fold": 0, "call": 0, "allin": 0 },
    "KQs": { "raise": 100, "fold": 0, "call": 0, "allin": 0 },
    "KJs": { "raise": 100, "fold": 0, "call": 0, "allin": 0 },
    "KTs": { "raise": 100, "fold": 0, "call": 0, "allin": 0 },
    "K9s": { "raise": 100, "fold": 0, "call": 0, "allin": 0 },
    "QJs": { "raise": 100, "fold": 0, "call": 0, "allin": 0 },
    "QTs": { "raise": 100, "fold": 0, "call": 0, "allin": 0 },
    "Q9s": { "raise": 100, "fold": 0, "call": 0, "allin": 0 },
    "JTs": { "raise": 100, "fold": 0, "call": 0, "allin": 0 },
    "J9s": { "raise": 100, "fold": 0, "call": 0, "allin": 0 },
    "T9s": { "raise": 100, "fold": 0, "call": 0, "allin": 0 },
    "AKo": { "raise": 100, "fold": 0, "call": 0, "allin": 0 },
    "AQo": { "raise": 100, "fold": 0, "call": 0, "allin": 0 },
    "AJo": { "raise": 100, "fold": 0, "call": 0, "allin": 0 },
    "ATo": { "raise": 100, "fold": 0, "call": 0, "allin": 0 },
    "KQo": { "raise": 100, "fold": 0, "call": 0, "allin": 0 },
    "KJo": { "raise": 75, "fold": 25, "call": 0, "allin": 0 },
    "QJo": { "raise": 25, "fold": 75, "call": 0, "allin": 0 },
    "KTo": { "raise": 50, "fold": 50, "call": 0, "allin": 0 },
    "55": { "raise": 50, "fold": 50, "call": 0, "allin": 0 },
    "K8s": { "raise": 50, "fold": 50, "call": 0, "allin": 0 },
    "K7s": { "raise": 50, "fold": 50, "call": 0, "allin": 0 },
    "K6s": { "raise": 50, "fold": 50, "call": 0, "allin": 0 },
    "K5s": { "raise": 50, "fold": 50, "call": 0, "allin": 0 },
    "44": { "raise": 50, "fold": 50, "call": 0, "allin": 0 },
    "33": { "raise": 50, "fold": 50, "call": 0, "allin": 0 },
    "22": { "raise": 50, "fold": 50, "call": 0, "allin": 0 },
    "T8s": { "raise": 50, "fold": 50, "call": 0, "allin": 0 },
    "98s": { "raise": 50, "fold": 50, "call": 0, "allin": 0 },
    "87s": { "raise": 50, "fold": 50, "call": 0, "allin": 0 },
    "76s": { "raise": 50, "fold": 50, "call": 0, "allin": 0 },
    "65s": { "raise": 50, "fold": 50, "call": 0, "allin": 0 },
    "54s": { "raise": 50, "fold": 50, "call": 0, "allin": 0 },
  },
};
