import type { PreflopStrategy } from '../types';

export const cash6max40bbCoVsOpen: PreflopStrategy = {
  id: 'cash-6max-40bb-co-vs-open',
  title: 'Cash 6-max 40bb CO vs Open 2.5x',
  meta: {
    format: 'CASH',
    players: 6,
    stackBB: 40,
    position: 'CO',
    action: 'vs-open',
    strategicNote: "Con 40bb, desde CO contra una apertura, la estrategia es más agresiva. Se realizan 3-bets por valor con un rango más amplio, se pagan menos manos especulativas y se foldean manos fácilmente dominadas. El objetivo es tomar la iniciativa o abandonar la mano preflop.",
  },
  stats: {
    raise: 8.7,
    call: 1.9,
    fold: 89.4,
    allin: 0.0,
  },
  range: {
    "AA":  { "allin": 0, "raise": 100,    "call": 0,     "fold": 0 },
    "AKs": { "allin": 0, "raise": 100,    "call": 0,     "fold": 0 },
    "AQs": { "allin": 0, "raise": 74.5, "call": 25.5, "fold": 0 },
    "AJs": { "allin": 0, "raise": 54.5, "call": 45.5, "fold": 0 },
    "ATs": { "allin": 0, "raise": 76, "call": 24, "fold": 0 },
    "A9s": { "allin": 0, "raise": 96, "call": 4, "fold": 0 },
    "A8s": { "allin": 0, "raise": 35.5, "call": 0, "fold": 64.5 },
    "A5s": { "allin": 0, "raise": 36, "call": 24.5, "fold": 39.5 },
    "AKo": { "allin": 0, "raise": 89.5, "call": 10.5, "fold": 0 },
    "KK": { "allin": 0, "raise": 100, "call": 0, "fold": 0 },
    "KQs": { "allin": 0, "raise": 52.5, "call": 47.5, "fold": 0 },
    "KJs": { "allin": 0, "raise": 71.5, "call": 28.5, "fold": 0 },
    "KTs": { "allin": 0, "raise": 84.5, "call": 15.5, "fold": 0 },
    "K9s": { "allin": 0, "raise": 29, "call": 0, "fold": 71 },
    "AQo": { "allin": 0, "raise": 84.5, "call": 15.5, "fold": 0 },
    "KQo": { "allin": 0, "raise": 28.5, "call": 0, "fold": 71.5 },
    "QQ": { "allin": 0, "raise": 100, "call": 0, "fold": 0 },
    "QJs": { "allin": 0, "raise": 86, "call": 14, "fold": 0 },
    "QTs": { "allin": 0, "raise": 55, "call": 23, "fold": 22 },
    "AJo": { "allin": 0, "raise": 42.5, "call": 0, "fold": 57.5 },
    "KJo": { "allin": 0, "raise": 9.5, "call": 0, "fold": 90.5 },
    "JJ": { "allin": 0, "raise": 85, "call": 15, "fold": 0 },
    "JTs": { "allin": 0, "raise": 73.5, "call": 26.5, "fold": 0 },
    "TT": { "allin": 0, "raise": 75, "call": 25, "fold": 0 },
    "T9s": { "allin": 0, "raise": 0, "call": 12.5, "fold": 87.5 },
    "99": { "allin": 0, "raise": 75.5, "call": 24.5, "fold": 0 },
    "88": { "allin": 0, "raise": 71.5, "call": 28.5, "fold": 0 },
    "77": { "allin": 0, "raise": 51.5, "call": 30.5, "fold": 18 },
    "66": { "allin": 0, "raise": 13, "call": 22, "fold": 65 },
    "55": { "allin": 0, "raise": 0, "call": 8.5, "fold": 91.5 },
    "44": { "allin": 0, "raise": 0, "call": 10.5, "fold": 89.5 },
    "33": { "allin": 0, "raise": 0, "call": 7, "fold": 93 },
    "22": { "allin": 0, "raise": 0, "call": 8, "fold": 92 }
  }
};
