import type { PreflopStrategy } from '../types';

export const mtt8max40bbHjVsOpen: PreflopStrategy = {
  id: 'mtt-8max-40bb-hj-vs-open',
  title: 'MTT 8-max 40bb HJ vs Open',
  meta: {
    format: 'MTT',
    players: 8,
    stackBB: 40,
    position: 'HJ',
    action: 'vs-open',
    strategicNote: 'Desde el Hijack (HJ) contra una apertura de una posición anterior, con un stack de 40bb, la estrategia se vuelve una mezcla de agresión y defensa. Se 3-betea un rango polarizado por valor y como semi-bluff. Se paga con manos que tienen buen potencial post-flop, y se foldean las manos más débiles para evitar situaciones complejas con un stack intermedio.',
  },
  stats: {
    raise: 10.8,
    call: 15.5,
    fold: 73.7,
    allin: 0,
  },
  range: {
    "AA":  { "allin": 0, "raise": 100, "call": 0,   "fold": 0 },
    "AKs": { "allin": 0, "raise": 100, "call": 0,   "fold": 0 },
    "AQs": { "allin": 0, "raise": 0,   "call": 100, "fold": 0 },
    "AJs": { "allin": 0, "raise": 0,   "call": 100, "fold": 0 },
    "ATs": { "allin": 0, "raise": 39,  "call": 61,  "fold": 0 },
    "A9s": { "allin": 0, "raise": 59,  "call": 41,  "fold": 0 },
    "A8s": { "allin": 0, "raise": 39,  "call": 38.5, "fold": 22.5 },
    "A7s": { "allin": 0, "raise": 23.5, "call": 33.5, "fold": 43 },
    "A5s": { "allin": 0, "raise": 0.5, "call": 99.5, "fold": 0 },
    "A4s": { "allin": 0, "raise": 0,   "call": 31,  "fold": 69 },
    "AKo": { "allin": 0, "raise": 49,  "call": 51,  "fold": 0 },
    "KK":  { "allin": 0, "raise": 86.5, "call": 13.5, "fold": 0 },
    "KQs": { "allin": 0, "raise": 0,   "call": 100, "fold": 0 },
    "KJs": { "allin": 0, "raise": 0,   "call": 100, "fold": 0 },
    "KTs": { "allin": 0, "raise": 48,  "call": 52,  "fold": 0 },
    "K9s": { "allin": 0, "raise": 40,  "call": 60,  "fold": 0 },
    "AQo": { "allin": 0, "raise": 48,  "call": 52,  "fold": 0 },
    "KQo": { "allin": 0, "raise": 33.5, "call": 66.5, "fold": 0 },
    "QQ":  { "allin": 0, "raise": 56,  "call": 44,  "fold": 0 },
    "QJs": { "allin": 0, "raise": 27.5, "call": 72.5, "fold": 0 },
    "QTs": { "allin": 0, "raise": 18,  "call": 82,  "fold": 0 },
    "AJo": { "allin": 0, "raise": 53,  "call": 47,  "fold": 0 },
    "KJo": { "allin": 0, "raise": 14.5, "call": 0,   "fold": 85.5 },
    "JJ":  { "allin": 0, "raise": 37,  "call": 63,  "fold": 0 },
    "JTs": { "allin": 0, "raise": 11.5, "call": 88.5, "fold": 0 },
    "J9s": { "allin": 0, "raise": 43.5, "call": 54.5, "fold": 2 },
    "ATo": { "allin": 0, "raise": 18.5, "call": 0,   "fold": 81.5 },
    "TT":  { "allin": 0, "raise": 37.5, "call": 62.5, "fold": 0 },
    "T9s": { "allin": 0, "raise": 9,   "call": 91,  "fold": 0 },
    "T8s": { "allin": 0, "raise": 0,   "call": 11,  "fold": 89 },
    "99":  { "allin": 0, "raise": 25.5, "call": 74.5, "fold": 0 },
    "98s": { "allin": 0, "raise": 0,   "call": 37,  "fold": 63 },
    "88":  { "allin": 0, "raise": 9.5, "call": 90.5, "fold": 0 },
    "77":  { "allin": 0, "raise": 9,   "call": 91,  "fold": 0 },
    "66":  { "allin": 0, "raise": 0,   "call": 100, "fold": 0 },
    "55":  { "allin": 0, "raise": 0.5, "call": 99.5, "fold": 0 },
    "44":  { "allin": 0, "raise": 0,   "call": 69,  "fold": 31 },
    "33":  { "allin": 0, "raise": 0,   "call": 52,  "fold": 48 },
    "22":  { "allin": 0, "raise": 0,   "call": 43,  "fold": 57 }
  }
};
