import type { PreflopStrategy } from '../types';

export const mtt8max20bbMpRfi: PreflopStrategy = {
  id: 'mtt-8max-20bb-mp-rfi',
  title: 'MTT 8-max 20bb MP RFI',
  meta: {
    format: 'MTT',
    players: 8,
    stackBB: 20,
    position: 'MP',
    action: 'RFI',
    strategicNote: 'Desde la posición media (MP) con 20bb, el rango de RFI (Raise First In) es más amplio que desde UTG. Se abren manos que tienen buena jugabilidad post-flop o que pueden ir all-in de forma rentable. La estrategia es agresiva, buscando robar las ciegas o jugar por todo el stack.',
  },
  stats: {
    raise: 22.3,
    call: 0,
    fold: 77.7,
    allin: 0,
  },
  range: {
    "AA": { "raise": 100 },
    "AKs": { "raise": 100 },
    "AQs": { "raise": 100 },
    "AJs": { "raise": 100 },
    "ATs": { "raise": 100 },
    "A9s": { "raise": 100 },
    "A8s": { "raise": 100 },
    "A7s": { "raise": 100 },
    "A6s": { "raise": 100 },
    "A5s": { "raise": 100 },
    "A4s": { "raise": 100 },
    "A3s": { "raise": 100 },
    "A2s": { "raise": 100 },
    "AKo": { "raise": 100 },
    "KK": { "raise": 100 },
    "KQs": { "raise": 100 },
    "KJs": { "raise": 100 },
    "KTs": { "raise": 100 },
    "K9s": { "raise": 100 },
    "K8s": { "raise": 100 },
    "K7s": { "raise": 100 },
    "K6s": { "raise": 57.5, "fold": 42.5 },
    "AQo": { "raise": 100 },
    "KQo": { "raise": 100 },
    "QQ": { "raise": 100 },
    "QJs": { "raise": 100 },
    "QTs": { "raise": 100 },
    "Q9s": { "raise": 100 },
    "Q8s": { "raise": 100 },
    "AJo": { "raise": 100 },
    "KJo": { "raise": 100 },
    "QJo": { "raise": 90, "fold": 10 },
    "JJ": { "raise": 100 },
    "JTs": { "raise": 100 },
    "J9s": { "raise": 100 },
    "ATo": { "raise": 100 },
    "KTo": { "raise": 100 },
    "QTo": { "raise": 27, "fold": 73 },
    "JTo": { "raise": 24, "fold": 76 },
    "TT": { "raise": 100 },
    "T9s": { "raise": 100 },
    "T8s": { "raise": 100 },
    "A9o": { "raise": 100 },
    "99": { "raise": 100 },
    "98s": { "raise": 100 },
    "97s": { "raise": 15.5, "fold": 84.5 },
    "88": { "raise": 100 },
    "87s": { "raise": 100 },
    "77": { "raise": 100 },
    "66": { "raise": 100 },
    "55": { "raise": 100 }
  },
};
