import type { PreflopStrategy } from '../types';

export const mtt8max40bbUtg1Vs3bet: PreflopStrategy = {
  id: 'mtt-8max-40bb-utg1-vs-3bet',
  title: 'MTT 8-max 40bb UTG+1 vs 3bet',
  meta: {
    format: 'MTT',
    players: 8,
    stackBB: 40,
    position: 'UTG+1',
    action: 'vs-3bet',
    strategicNote: 'Desde UTG+1 con 40bb, al enfrentar un 3-bet, la estrategia es una mezcla de agresión y defensa. Con un stack intermedio, se va all-in con un rango de valor fuerte, se paga con manos que tienen buenas pot odds y jugabilidad post-flop, y se foldean las manos más débiles para evitar situaciones dominadas fuera de posición.',
  },
  stats: {
    raise: 0.0,
    call: 9.8,
    fold: 86.1,
    allin: 4.1,
  },
  range: {
    "AA":  { "allin": 65.6, "raise": 0, "call": 34.4, "fold": 0 },
    "AKs": { "allin": 100,  "raise": 0, "call": 0,    "fold": 0 },
    "AQs": { "allin": 0,    "raise": 0, "call": 100,  "fold": 0 },
    "AJs": { "allin": 0,    "raise": 0, "call": 100,  "fold": 0 },
    "ATs": { "allin": 0,    "raise": 0, "call": 100,  "fold": 0 },
    "A9s": { "allin": 0,    "raise": 0, "call": 100,  "fold": 0 },
    "A8s": { "allin": 2,    "raise": 0, "call": 98,   "fold": 0 },
    "A7s": { "allin": 9,    "raise": 0, "call": 22.6, "fold": 68.4 },
    "A6s": { "allin": 0,    "raise": 0, "call": 42,   "fold": 58 },
    "A5s": { "allin": 100,  "raise": 0, "call": 0,    "fold": 0 },
    "A4s": { "allin": 100,  "raise": 0, "call": 0,    "fold": 0 },
    "A3s": { "allin": 88.8, "raise": 0, "call": 11.2, "fold": 0 },
    "A2s": { "allin": 34,   "raise": 0, "call": 66,   "fold": 0 },
    "AKo": { "allin": 100,  "raise": 0, "call": 0,    "fold": 0 },
    "KK":  { "allin": 100,  "raise": 0, "call": 0,    "fold": 0 },
    "KQs": { "allin": 0,    "raise": 0, "call": 100,  "fold": 0 },
    "KJs": { "allin": 0,    "raise": 0, "call": 100,  "fold": 0 },
    "KTs": { "allin": 0,    "raise": 0, "call": 100,  "fold": 0 },
    "K9s": { "allin": 0,    "raise": 0, "call": 100,  "fold": 0 },
    "K7s": { "allin": 0,    "raise": 0, "call": 94.6502, "fold": 5.3498 },
    "K6s": { "allin": 0,    "raise": 0, "call": 100,  "fold": 0 },
    "AQo": { "allin": 0,    "raise": 0, "call": 100,  "fold": 0 },
    "QQ":  { "allin": 100,  "raise": 0, "call": 0,    "fold": 0 },
    "QJs": { "allin": 0,    "raise": 0, "call": 100,  "fold": 0 },
    "QTs": { "allin": 0,    "raise": 0, "call": 100,  "fold": 0 },
    "AJo": { "allin": 0,    "raise": 0, "call": 14,   "fold": 86 },
    "JJ":  { "allin": 100,  "raise": 0, "call": 0,    "fold": 0 },
    "JTs": { "allin": 0,    "raise": 0, "call": 100,  "fold": 0 },
    "J9s": { "allin": 0,    "raise": 0, "call": 58.8, "fold": 41.2 },
    "TT":  { "allin": 61.4, "raise": 0, "call": 38.6, "fold": 0 },
    "T9s": { "allin": 0,    "raise": 0, "call": 100,  "fold": 0 },
    "T8s": { "allin": 0,    "raise": 0, "call": 95,   "fold": 5 },
    "99":  { "allin": 0,    "raise": 0, "call": 100,  "fold": 0 },
    "98s": { "allin": 0,    "raise": 0, "call": 100,  "fold": 0 },
    "88":  { "allin": 0,    "raise": 0, "call": 100,  "fold": 0 },
    "77":  { "allin": 0,    "raise": 0, "call": 100,  "fold": 0 },
    "66":  { "allin": 0,    "raise": 0, "call": 100,  "fold": 0 },
    "55":  { "allin": 0,    "raise": 0, "call": 100,  "fold": 0 },
    "44":  { "allin": 0,    "raise": 0, "call": 100,  "fold": 0 }
  },
};
