import type { PreflopStrategy } from '../types';

export const mtt8max20bbUtg1Rfi: PreflopStrategy = {
  id: 'mtt-8max-20bb-utg1-rfi',
  title: 'MTT 8-max 20bb UTG+1 RFI',
  meta: {
    format: 'MTT',
    players: 8,
    stackBB: 20,
    position: 'UTG+1',
    action: 'RFI',
    strategicNote: 'Desde UTG+1 con 20bb, el rango de RFI se mantiene ajustado pero se amplía ligeramente en comparación con UTG. La estrategia se centra en abrir manos que tienen buena equity para jugar por todo el stack, ya sea preflop o postflop. La agresión es clave para acumular fichas con un stack corto.',
  },
  stats: {
    raise: 17.0,
    call: 0,
    fold: 83.0,
    allin: 0,
  },
  range: {
    "AA":  { "raise": 100 },
    "AKs": { "raise": 100 },
    "AQs": { "raise": 100 },
    "AJs": { "raise": 100 },
    "ATs": { "raise": 100 },
    "A9s": { "raise": 100 },
    "A8s": { "raise": 100 },
    "A7s": { "raise": 100 },
    "A6s": { "raise": 100 },
    "A5s": { "raise": 100 },
    "A4s": { "raise": 100 },
    "AKo": { "raise": 100 },
    "KK":  { "raise": 100 },
    "KQs": { "raise": 100 },
    "KJs": { "raise": 100 },
    "KTs": { "raise": 100 },
    "K9s": { "raise": 100 },
    "K8s": { "raise": 100 },
    "K7s": { "raise": 40.5, "fold": 59.5 },
    "AQo": { "raise": 100 },
    "KQo": { "raise": 100 },
    "QQ":  { "raise": 100 },
    "QJs": { "raise": 100 },
    "QTs": { "raise": 100 },
    "Q9s": { "raise": 100 },
    "Q8s": { "raise": 95, "fold": 5 },
    "AJo": { "raise": 100 },
    "KJo": { "raise": 100 },
    "QJo": { "raise": 90, "fold": 10 },
    "QTo": { "raise": 4.5, "fold": 95.5 },
    "JJ":  { "raise": 100 },
    "JTs": { "raise": 100 },
    "J9s": { "raise": 100 },
    "ATo": { "raise": 100 },
    "KTo": { "raise": 100 },
    "TT":  { "raise": 100 },
    "T9s": { "raise": 100 },
    "T8s": { "raise": 100 },
    "A9o": { "raise": 100 },
    "99":  { "raise": 100 },
    "98s": { "raise": 86, "fold": 14 },
    "88":  { "raise": 100 },
    "77":  { "raise": 100 },
    "66":  { "raise": 100 },
    "55":  { "raise": 48.5, "fold": 51.5 }
  },
};
