import type { PreflopStrategy } from '../types';

export const mtt8max20bbUtgRfi: PreflopStrategy = {
  id: 'mtt-8max-20bb-utg-rfi',
  title: 'MTT 8-max 20bb UTG RFI',
  meta: {
    format: 'MTT',
    players: 8,
    stackBB: 20,
    position: 'UTG',
    action: 'RFI',
    strategicNote: 'Con un stack de 20bb desde UTG, nuestra estrategia de RFI es muy ajustada. Se abren principalmente manos fuertes para ir all-in post-flop con comodidad o para tener una buena equity si nos pagan. El rango es casi exclusivamente de raise o fold, eliminando los calls para no crear pozos multi-way fuera de posición con un stack comprometido.',
  },
  stats: {
    raise: 19.5,
    call: 0,
    fold: 80.5,
    allin: 0,
  },
  range: {
    "AA": { "raise": 100 },
    "KK": { "raise": 100 },
    "QQ": { "raise": 100 },
    "JJ": { "raise": 100 },
    "TT": { "raise": 100 },
    "99": { "raise": 100 },
    "88": { "raise": 100 },
    "77": { "raise": 100 },
    "66": { "raise": 100 },
    "AKs": { "raise": 100 },
    "AQs": { "raise": 100 },
    "AJs": { "raise": 100 },
    "ATs": { "raise": 100 },
    "A9s": { "raise": 100 },
    "A8s": { "raise": 100 },
    "A7s": { "raise": 100 },
    "A6s": { "raise": 100 },
    "A5s": { "raise": 100 },
    "A4s": { "raise": 100 },
    "AKo": { "raise": 100 },
    "AQo": { "raise": 100 },
    "AJo": { "raise": 100 },
    "ATo": { "raise": 100 },
    "A9o": { "raise": 100 },
    "KQs": { "raise": 100 },
    "KJs": { "raise": 100 },
    "KTs": { "raise": 100 },
    "K9s": { "raise": 100 },
    "K8s": { "raise": 100 },
    "KQo": { "raise": 100 },
    "KJo": { "raise": 100 },
    "KTo": { "raise": 100 },
    "QJs": { "raise": 100 },
    "QTs": { "raise": 100 },
    "Q9s": { "raise": 100 },
    "Q8s": { "raise": 100 },
    "QJo": { "raise": 100 },
    "JTs": { "raise": 100 },
    "J9s": { "raise": 100 },
    "T9s": { "raise": 100 },
    "T8s": { "raise": 100 },
    "98s": { "raise": 100 }
  },
};
