import type { PreflopStrategy } from '../types';

export const mtt8max40bbUtgVs3bet: PreflopStrategy = {
  id: 'mtt-8max-40bb-utg-vs-3bet',
  title: 'MTT 8-max 40bb UTG vs 3bet',
  meta: {
    format: 'MTT',
    players: 8,
    stackBB: 40,
    position: 'UTG',
    action: 'vs-3bet',
    strategicNote: 'Desde UTG con 40bb, al enfrentar un 3-bet, la estrategia es una mezcla de agresión y defensa. Se va all-in con un rango de valor fuerte, se paga con manos que tienen buenas pot odds y jugabilidad post-flop, y se foldean las manos más débiles para evitar situaciones dominadas fuera de posición.',
  },
  stats: {
    raise: 0,
    call: 8.3,
    fold: 8.0,
    allin: 3.7,
  },
  range: {
    "AA":  { "allin": 73.5, "raise": 0, "call": 26.5, "fold": 0 },
    "AKs": { "allin": 100,  "raise": 0, "call": 0,    "fold": 0 },
    "AQs": { "allin": 0,    "raise": 0, "call": 100,  "fold": 0 },
    "AJs": { "allin": 0,    "raise": 0, "call": 100,  "fold": 0 },
    "ATs": { "allin": 30,   "raise": 0, "call": 70,   "fold": 0 },
    "A9s": { "allin": 0,    "raise": 0, "call": 77,   "fold": 23 },
    "A8s": { "allin": 0,    "raise": 0, "call": 20,   "fold": 80 },
    "A7s": { "allin": 0,    "raise": 0, "call": 29,   "fold": 71 },
    "A6s": { "allin": 0,    "raise": 0, "call": 40.5, "fold": 59.5 },
    "A5s": { "allin": 100,  "raise": 0, "call": 0,    "fold": 0 },
    "A4s": { "allin": 100,  "raise": 0, "call": 0,    "fold": 0 },
    "A3s": { "allin": 33,   "raise": 0, "call": 67,   "fold": 0 },
    "AKo": { "allin": 100,  "raise": 0, "call": 0,    "fold": 0 },
    "KK":  { "allin": 100,  "raise": 0, "call": 0,    "fold": 0 },
    "KQs": { "allin": 0,    "raise": 0, "call": 100,  "fold": 0 },
    "KJs": { "allin": 0,    "raise": 0, "call": 100,  "fold": 0 },
    "KTs": { "allin": 0,    "raise": 0, "call": 100,  "fold": 0 },
    "K9s": { "allin": 0,    "raise": 0, "call": 54,   "fold": 46 },
    "AQo": { "allin": 0,    "raise": 0, "call": 100,  "fold": 0 },
    "QQ":  { "allin": 100,  "raise": 0, "call": 0,    "fold": 0 },
    "QJs": { "allin": 0,    "raise": 0, "call": 100,  "fold": 0 },
    "QTs": { "allin": 0,    "raise": 0, "call": 86.5, "fold": 13.5 },
    "JJ":  { "allin": 88.5, "raise": 0, "call": 11.5, "fold": 0 },
    "JTs": { "allin": 0,    "raise": 0, "call": 100,  "fold": 0 },
    "J9s": { "allin": 0,    "raise": 0, "call": 28,   "fold": 72 },
    "TT":  { "allin": 8.5,  "raise": 0, "call": 91.5, "fold": 0 },
    "T9s": { "allin": 0,    "raise": 0, "call": 100,  "fold": 0 },
    "T8s": { "allin": 0,    "raise": 0, "call": 48.46,"fold": 51.54 },
    "99":  { "allin": 0,    "raise": 0, "call": 100,  "fold": 0 },
    "98s": { "allin": 0,    "raise": 0, "call": 100,  "fold": 0 },
    "88":  { "allin": 0,    "raise": 0, "call": 100,  "fold": 0 },
    "77":  { "allin": 0,    "raise": 0, "call": 100,  "fold": 0 },
    "66":  { "allin": 0,    "raise": 0, "call": 100,  "fold": 0 },
    "55":  { "allin": 0,    "raise": 0, "call": 100,  "fold": 0 },
    "44":  { "allin": 0,    "raise": 0, "call": 100,  "fold": 0 }
  },
};
