import type { PreflopStrategy } from '../types';

export const mtt8max40bbCoVsOpen: PreflopStrategy = {
  id: 'mtt-8max-40bb-co-vs-open',
  title: 'MTT 8-max 40bb CO vs Open',
  meta: {
    format: 'MTT',
    players: 8,
    stackBB: 40,
    position: 'CO',
    action: 'vs-open',
    strategicNote: 'Desde el Cutoff con un stack de 40bb, al enfrentar una apertura, la estrategia es una mezcla de 3-bet y call. Se 3-betea un rango polarizado de manos premium y bluffs con buenos bloqueadores. Se paga con manos que tienen buen potencial post-flop en posición. Las manos más débiles se retiran para evitar situaciones dominadas con un stack intermedio.',
  },
  stats: {
    raise: 10.8,
    call: 15.5,
    fold: 73.7,
    allin: 0,
  },
  range: {
    "AA":  { "allin": 0, "raise": 100, "call": 0,   "fold": 0 },
    "AKs": { "allin": 0, "raise": 100, "call": 0,   "fold": 0 },
    "AQs": { "allin": 0, "raise": 0,   "call": 100, "fold": 0 },
    "AJs": { "allin": 0, "raise": 0,   "call": 100, "fold": 0 },
    "ATs": { "allin": 0, "raise": 0,   "call": 100, "fold": 0 },
    "A9s": { "allin": 0, "raise": 33,   "call": 67,   "fold": 0 },
    "A8s": { "allin": 0, "raise": 33.5, "call": 66.5, "fold": 0 },
    "A7s": { "allin": 0, "raise": 32.5, "call": 67.5, "fold": 0 },
    "A6s": { "allin": 0, "raise": 0,   "call": 45,  "fold": 55 },
    "A5s": { "allin": 0, "raise": 7,   "call": 93,  "fold": 0 },
    "A4s": { "allin": 0, "raise": 0,   "call": 100, "fold": 0 },
    "A3s": { "allin": 0, "raise": 0,   "call": 19.5, "fold": 80.5 },
    "AKo": { "allin": 0, "raise": 44,  "call": 56,  "fold": 0 },
    "KK":  { "allin": 0, "raise": 88,  "call": 12,  "fold": 0 },
    "KQs": { "allin": 0, "raise": 0,   "call": 100, "fold": 0 },
    "KJs": { "allin": 0, "raise": 0,   "call": 100, "fold": 0 },
    "KTs": { "allin": 0, "raise": 33,  "call": 67,  "fold": 0 },
    "K9s": { "allin": 0, "raise": 37,  "call": 63,  "fold": 0 },
    "K8s": { "allin": 0, "raise": 0.5, "call": 22.5, "fold": 77 },
    "K6s": { "allin": 0, "raise": 0,   "call": 30,  "fold": 70 },
    "AQo": { "allin": 0, "raise": 41.5, "call": 58.5, "fold": 0 },
    "KQo": { "allin": 0, "raise": 20,  "call": 80,  "fold": 0 },
    "QQ":  { "allin": 0, "raise": 43.5, "call": 56.5, "fold": 0 },
    "QJs": { "allin": 0, "raise": 14.5, "call": 85.5, "fold": 0 },
    "QTs": { "allin": 0, "raise": 9.5, "call": 90.5, "fold": 0 },
    "Q9s": { "allin": 0, "raise": 46.5, "call": 53.5, "fold": 0 },
    "AJo": { "allin": 0, "raise": 38,  "call": 62,  "fold": 0 },
    "KJo": { "allin": 0, "raise": 28.5, "call": 23,  "fold": 48.5 },
    "JJ":  { "allin": 0, "raise": 37,  "call": 63,  "fold": 0 },
    "JTs": { "allin": 0, "raise": 4,   "call": 96,  "fold": 0 },
    "J9s": { "allin": 0, "raise": 33,  "call": 67,  "fold": 0 },
    "ATo": { "allin": 0, "raise": 37,  "call": 4,   "fold": 59 },
    "TT":  { "allin": 0, "raise": 23.5, "call": 76.5, "fold": 0 },
    "T9s": { "allin": 0, "raise": 4,   "call": 96,  "fold": 0 },
    "T8s": { "allin": 0, "raise": 25,  "call": 75,  "fold": 0 },
    "99":  { "allin": 0, "raise": 22,  "call": 78,  "fold": 0 },
    "98s": { "allin": 0, "raise": 8,   "call": 92,  "fold": 0 },
    "88":  { "allin": 0, "raise": 11.5, "call": 88.5, "fold": 0 },
    "87s": { "allin": 0, "raise": 0,   "call": 41.5, "fold": 58.5 },
    "77":  { "allin": 0, "raise": 0,   "call": 100, "fold": 0 },
    "66":  { "allin": 0, "raise": 0,   "call": 100, "fold": 0 },
    "55":  { "allin": 0, "raise": 0,   "call": 100, "fold": 0 },
    "44":  { "allin": 0, "raise": 0,   "call": 100, "fold": 0 },
    "33":  { "allin": 0, "raise": 0,   "call": 100, "fold": 0 },
    "22":  { "allin": 0, "raise": 0,   "call": 100, "fold": 0 }
  }
};
