import type { PreflopStrategy } from '../types';

export const mtt8max100bbUtg1Vs3bet: PreflopStrategy = {
  id: 'mtt-8max-100bb-utg1-vs-3bet',
  title: 'MTT 8-max 100bb UTG+1 vs 3bet',
  meta: {
    format: 'MTT',
    players: 8,
    stackBB: 100,
    position: 'UTG+1',
    action: 'vs-3bet',
    strategicNote: 'Desde UTG+1 con 100bb, al enfrentar un 3-bet, la estrategia es una mezcla de 4-bet, call y fold. Con un stack profundo, se polariza el rango de 4-bet con manos de valor y faroles, mientras que se paga con manos que tienen buen potencial post-flop para aprovechar las odds implícitas. Las manos más débiles se retiran para evitar situaciones complicadas fuera de posición.',
  },
  stats: {
    raise: 17.5,
    call: 35.2,
    fold: 42.1,
    allin: 5.2,
  },
  range: {
    "AA":  { "allin": 0,    "raise": 100,  "call": 0,     "fold": 0 },
    "AKs": { "allin": 14,   "raise": 86,   "call": 0,     "fold": 0 },
    "AQs": { "allin": 0,    "raise": 35,   "call": 65,    "fold": 0 },
    "AJs": { "allin": 0,    "raise": 39.5, "call": 60.5,  "fold": 0 },
    "ATs": { "allin": 0,    "raise": 31.5, "call": 68.5,  "fold": 0 },
    "A9s": { "allin": 0,    "raise": 0,    "call": 96.5,  "fold": 3.5 },
    "A8s": { "allin": 0,    "raise": 9.54774, "call": 52.76386, "fold": 37.6884 },
    "A7s": { "allin": 0,    "raise": 0.5,  "call": 11,    "fold": 88.5 },
    "A5s": { "allin": 0,    "raise": 29.5, "call": 70.5,  "fold": 0 },
    "A4s": { "allin": 0,    "raise": 14,   "call": 75,    "fold": 11 },
    "A3s": { "allin": 0,    "raise": 0,    "call": 38.5,  "fold": 61.5 },
    "AKo": { "allin": 57.5, "raise": 7,    "call": 35.5,  "fold": 0 },
    "KK":  { "allin": 46.5, "raise": 53.5, "call": 0,     "fold": 0 },
    "KQs": { "allin": 0,    "raise": 16,   "call": 84,    "fold": 0 },
    "KJs": { "allin": 0,    "raise": 20,   "call": 80,    "fold": 0 },
    "KTs": { "allin": 0,    "raise": 17,   "call": 83,    "fold": 0 },
    "AQo": { "allin": 0,    "raise": 17.5, "call": 51.5,  "fold": 31 },
    "QQ":  { "allin": 0,    "raise": 28,   "call": 72,    "fold": 0 },
    "QJs": { "allin": 0,    "raise": 7.5,  "call": 92.5,  "fold": 0 },
    "QTs": { "allin": 0,    "raise": 0,    "call": 70.5,  "fold": 29.5 },
    "JJ":  { "allin": 0,    "raise": 31.5, "call": 68.5,  "fold": 0 },
    "JTs": { "allin": 0,    "raise": 16,   "call": 84,    "fold": 0 },
    "J9s": { "allin": 0,    "raise": 0,    "call": 21.5,  "fold": 78.5 },
    "TT":  { "allin": 0,    "raise": 21.5, "call": 78.5,  "fold": 0 },
    "T9s": { "allin": 0,    "raise": 18,   "call": 74.5,  "fold": 7.5 },
    "T8s": { "allin": 0,    "raise": 0,    "call": 20,    "fold": 80 },
    "99":  { "allin": 0,    "raise": 8,    "call": 92,    "fold": 0 },
    "98s": { "allin": 0,    "raise": 1,    "call": 69.5,  "fold": 29.5 },
    "88":  { "allin": 0,    "raise": 5,    "call": 95,    "fold": 0 },
    "77":  { "allin": 0,    "raise": 0.5,  "call": 99.5,  "fold": 0 },
    "66":  { "allin": 0,    "raise": 0,    "call": 100,   "fold": 0 },
    "55":  { "allin": 0,    "raise": 0,    "call": 81.5,  "fold": 18.5 },
    "44":  { "allin": 0,    "raise": 0,    "call": 84.5,  "fold": 15.5 },
    "33":  { "allin": 0,    "raise": 0,    "call": 71.5,  "fold": 28.5 },
    "22":  { "allin": 0,    "raise": 0,    "call": 73,    "fold": 27 }
  }
};
