import type { PreflopStrategy } from '../types';

export const mtt8max100bbUtgRfi: PreflopStrategy = {
  id: 'mtt-8max-100bb-utg-rfi',
  title: 'MTT 8-max 100bb UTG RFI',
  meta: {
    format: 'MTT',
    players: 8,
    stackBB: 100,
    position: 'UTG',
    action: 'RFI',
    strategicNote: 'Desde UTG en una mesa de 8-max de MTT, nuestro rango de apertura es muy ajustado. Al ser los primeros en hablar, nos enfrentamos a 7 jugadores, por lo que solo abrimos manos premium que mantengan su equity post-flop. La estrategia se basa en la fuerza bruta de nuestras cartas, no en la posición.',
  },
  stats: {
    raise: 14.5,
    call: 0.0,
    fold: 85.5,
    allin: 0.0,
  },
  range: {
    "AA":  { "allin": 0, "raise": 100, "call": 0, "fold": 0 },
    "AKs": { "allin": 0, "raise": 100, "call": 0, "fold": 0 },
    "AQs": { "allin": 0, "raise": 100, "call": 0, "fold": 0 },
    "AJs": { "allin": 0, "raise": 100, "call": 0, "fold": 0 },
    "ATs": { "allin": 0, "raise": 100, "call": 0, "fold": 0 },
    "A9s": { "allin": 0, "raise": 100, "call": 0, "fold": 0 },
    "A8s": { "allin": 0, "raise": 100, "call": 0, "fold": 0 },
    "A7s": { "allin": 0, "raise": 100, "call": 0, "fold": 0 },
    "A6s": { "allin": 0, "raise": 100, "call": 0, "fold": 0 },
    "A5s": { "allin": 0, "raise": 100, "call": 0, "fold": 0 },
    "A4s": { "allin": 0, "raise": 100, "call": 0, "fold": 0 },
    "A3s": { "allin": 0, "raise": 40.5, "call": 0, "fold": 59.5 },
    "AKo": { "allin": 0, "raise": 100, "call": 0, "fold": 0 },
    "KK":  { "allin": 0, "raise": 100, "call": 0, "fold": 0 },
    "KQs": { "allin": 0, "raise": 100, "call": 0, "fold": 0 },
    "KJs": { "allin": 0, "raise": 100, "call": 0, "fold": 0 },
    "KTs": { "allin": 0, "raise": 100, "call": 0, "fold": 0 },
    "K9s": { "allin": 0, "raise": 100, "call": 0, "fold": 0 },
    "K8s": { "allin": 0, "raise": 41, "call": 0, "fold": 59 },
    "AQo": { "allin": 0, "raise": 100, "call": 0, "fold": 0 },
    "KQo": { "allin": 0, "raise": 100, "call": 0, "fold": 0 },
    "QQ":  { "allin": 0, "raise": 100, "call": 0, "fold": 0 },
    "QJs": { "allin": 0, "raise": 100, "call": 0, "fold": 0 },
    "QTs": { "allin": 0, "raise": 100, "call": 0, "fold": 0 },
    "Q9s": { "allin": 0, "raise": 100, "call": 0, "fold": 0 },
    "AJo": { "allin": 0, "raise": 100, "call": 0, "fold": 0 },
    "KJo": { "allin": 0, "raise": 34, "call": 0, "fold": 66 },
    "QJo": { "allin": 0, "raise": 9,  "call": 0, "fold": 91 },
    "JJ":  { "allin": 0, "raise": 100, "call": 0, "fold": 0 },
    "JTs": { "allin": 0, "raise": 100, "call": 0, "fold": 0 },
    "J9s": { "allin": 0, "raise": 100, "call": 0, "fold": 0 },
    "ATo": { "allin": 0, "raise": 25.5, "call": 0, "fold": 74.5 },
    "JTo": { "allin": 0, "raise": 5.5,  "call": 0, "fold": 94.5 },
    "TT":  { "allin": 0, "raise": 100, "call": 0, "fold": 0 },
    "T9s": { "allin": 0, "raise": 100, "call": 0, "fold": 0 },
    "T8s": { "allin": 0, "raise": 76, "call": 0, "fold": 24 },
    "99":  { "allin": 0, "raise": 100, "call": 0, "fold": 0 },
    "98s": { "allin": 0, "raise": 54, "call": 0, "fold": 46 },
    "88":  { "allin": 0, "raise": 100, "call": 0, "fold": 0 },
    "87s": { "allin": 0, "raise": 31.5, "call": 0, "fold": 68.5 },
    "77":  { "allin": 0, "raise": 100, "call": 0, "fold": 0 },
    "76s": { "allin": 0, "raise": 24, "call": 0, "fold": 76 },
    "66":  { "allin": 0, "raise": 100, "call": 0, "fold": 0 },
    "65s": { "allin": 0, "raise": 19.5, "call": 0, "fold": 80.5 },
    "55":  { "allin": 0, "raise": 100, "call": 0, "fold": 0 },
    "44":  { "allin": 0, "raise": 63.5, "call": 0, "fold": 36.5 },
    "33":  { "allin": 0, "raise": 51,   "call": 0, "fold": 49 },
    "22":  { "allin": 0, "raise": 55.5, "call": 0, "fold": 44.5 }
  },
};
