import type { PreflopStrategy } from '../types';

export const mtt8max40bbMpVsOpen: PreflopStrategy = {
  id: 'mtt-8max-40bb-mp-vs-open',
  title: 'MTT 8-max 40bb MP vs Open',
  meta: {
    format: 'MTT',
    players: 8,
    stackBB: 40,
    position: 'MP',
    action: 'vs-open',
    strategicNote: 'Desde la Posición Media (MP) con 40bb, al enfrentar una apertura de una posición anterior (UTG, UTG+1), la estrategia es una mezcla de agresión y defensa. Se hacen 3-bets por valor y como semi-bluff, y se paga con manos que tienen buen potencial para jugar post-flop, aunque con más cautela que con stacks profundos debido al SPR más bajo.',
  },
  stats: {
    raise: 8.4,
    call: 8.1,
    fold: 83.5,
    allin: 0.0,
  },
  range: {
    "AA":  { "allin": 0, "raise": 100, "call": 0,   "fold": 0 },
    "AKs": { "allin": 0, "raise": 100, "call": 0,   "fold": 0 },
    "AQs": { "allin": 0, "raise": 0,   "call": 100, "fold": 0 },
    "AJs": { "allin": 0, "raise": 0,   "call": 100, "fold": 0 },
    "ATs": { "allin": 0, "raise": 31,  "call": 69,  "fold": 0 },
    "A9s": { "allin": 0, "raise": 60,  "call": 40,  "fold": 0 },
    "A8s": { "allin": 0, "raise": 40,  "call": 38.5, "fold": 21.5 },
    "A5s": { "allin": 0, "raise": 0,   "call": 65,  "fold": 35 },
    "AKo": { "allin": 0, "raise": 55.5, "call": 44,  "fold": 0.5 },
    "KK":  { "allin": 0, "raise": 89,  "call": 11,  "fold": 0 },
    "KQs": { "allin": 0, "raise": 0,   "call": 100, "fold": 0 },
    "KJs": { "allin": 0, "raise": 52,  "call": 48,  "fold": 0 },
    "KTs": { "allin": 0, "raise": 65,  "call": 35,  "fold": 0 },
    "K9s": { "allin": 0, "raise": 52.7054, "call": 41.6834, "fold": 5.6112 },
    "AQo": { "allin": 0, "raise": 61.5, "call": 38.5, "fold": 0 },
    "KQo": { "allin": 0, "raise": 28.5, "call": 27.5, "fold": 44 },
    "QQ":  { "allin": 0, "raise": 65,  "call": 35,  "fold": 0 },
    "QJs": { "allin": 0, "raise": 49.5, "call": 50.5, "fold": 0 },
    "QTs": { "allin": 0, "raise": 23.5, "call": 76.5, "fold": 0 },
    "AJo": { "allin": 0, "raise": 58.5, "call": 25,  "fold": 16.5 },
    "KJo": { "allin": 0, "raise": 10,  "call": 0,   "fold": 90 },
    "JJ":  { "allin": 0, "raise": 37.5, "call": 62.5, "fold": 0 },
    "JTs": { "allin": 0, "raise": 24,  "call": 76,  "fold": 0 },
    "TT":  { "allin": 0, "raise": 46.5, "call": 53.5, "fold": 0 },
    "T9s": { "allin": 0, "raise": 0,   "call": 60,  "fold": 40 },
    "99":  { "allin": 0, "raise": 33.5, "call": 66.5, "fold": 0 },
    "88":  { "allin": 0, "raise": 16.5, "call": 83.5, "fold": 0 },
    "77":  { "allin": 0, "raise": 10,  "call": 90,  "fold": 0 },
    "66":  { "allin": 0, "raise": 0,   "call": 83.5, "fold": 16.5 },
    "55":  { "allin": 0, "raise": 0,   "call": 50.5, "fold": 49.5 },
    "44":  { "allin": 0, "raise": 0,   "call": 34.5, "fold": 65.5 },
    "33":  { "allin": 0, "raise": 0,   "call": 19,  "fold": 81 },
    "22":  { "allin": 0, "raise": 0,   "call": 14.5, "fold": 85.5 }
  }
};
